spring:
  application:
    name: discovery-server
server:
  port: 8761
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    # Will run the evict task every 3 seconds
    eviction-interval-timer-in-ms: 3000
