server:
  port: 8091 # change to 0 for dynamically allocated port
property1: 'Sample service meeting prop 1 - generic'
property2: 'Sample service meeting prop 2 - generic'
# To enable actuator endpoints:
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

# Sample configuration useful when e.g. killing app forcefully
eureka:
  instance:
    # Indicates how often app sends heartbeat to Eureka server
    lease-renewal-interval-in-seconds: 30
    # Indicates how long Eureka server waits for heartbeat before removing instance from discovery
    lease-expiration-duration-in-seconds: 90

# Feign client
feign:
  client:
    config:
      example-service:
#        read-timeout: 100
#        connect-timeout: 100
        logger-level: full
