server:
  port: 0 # dynamically allocates port
property1: 'Sample service meeting prop 1 - generic'
property2: 'Sample service meeting prop 2 - generic'
# To enable actuator endpoints:
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
